import Head from 'next/head';
import axios from 'axios';
import { Video } from '@/types';
import { NoResults, VideoCard } from '@/components';

interface HomeProps {
  videos: Video[];
}

export default function Home({ videos }: HomeProps) {
  return (
    <>
      <Head>
        <title>Tiktok clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-10 videos h-full">
        {videos?.length ? (
          videos?.map((video: Video) => (
            <VideoCard post={video} key={video._id} />
          ))
        ) : (
          <NoResults text={`No Videos`} />
        )}
      </div>
    </>
  );
}

export const getServerSideProps = async () => {
  const { data } = await axios.get(`http://localhost:3000/api/post`);
  return {
    props: {
      videos: data,
    },
  };
};
